version: "3"

services:
  backend:
    build: ./students-backend
    container_name: students-backend
    command: bash
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./students-backend/:/app
    depends_on:
      - user-engine
    ports:
      - 3000:3000
    environment:
      JWT_SECRET: secretJWT
    network_mode: host

  user-engine:
    build: ./user-engine
    container_name: user-engine
    command: bash
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./user-engine/:/app
    depends_on:
      - create-student-engine
    ports:
      - 5555:5555
    environment:
      DATABASE_URL: postgres://postgres:password@localhost:5432/Students?schema=public
    network_mode: host

  create-student-engine:
    build: ./create-student-engine
    container_name: create-student-engine
    command: bash
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./create-student-engine/:/app
    depends_on:
      - find-student-engine
    environment:
      DATABASE_URL: postgres://postgres:password@localhost:5432/Students?schema=public
    network_mode: host

  find-student-engine:
    build: ./find-student-engine
    container_name: find-student-engine
    command: bash
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./find-student-engine/:/app
    depends_on:
      - update-student-engine
    environment:
      DATABASE_URL: postgres://postgres:password@localhost:5432/Students?schema=public
    network_mode: host

  update-student-engine:
    build: ./update-student-engine
    container_name: update-student-engine
    command: bash
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./update-student-engine/:/app
    depends_on:
      - delete-student-engine
    environment:
      DATABASE_URL: postgres://postgres:password@localhost:5432/Students?schema=public
    network_mode: host

  delete-student-engine:
    build: ./delete-student-engine
    container_name: delete-student-engine
    command: bash
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./delete-student-engine/:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@localhost:5432/Students?schema=public
    network_mode: host

  kafdrop:
    container_name: kafdrop-container
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
  kafka:
    container_name: kafka-container
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    depends_on:
      - db
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"


  db:
    container_name: students-db
    image: postgres
    restart: "no"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Students
    network_mode: host