version: "3"

services:
  backend:
    build: ./students-backend
    container_name: students-backend
    command: bash
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./students-backend/:/app
    depends_on:
      - create-student-engine
    ports:
      - 3000:3000
    environment:
      JWT_SECRET: secretJWT
    network_mode: host

  create-student-engine:
    build: ./create-student-engine
    container_name: create-student-engine
    command: bash
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./create-student-engine/:/app
    depends_on:
      - db
    ports:
      - 5555:5555
    environment:
      DATABASE_URL: postgres://postgres:password@localhost:5432/Students?schema=public
    network_mode: host

  find-student-engine:
    build: ./find-student-engine
    container_name: find-student-engine
    command: bash
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./find-student-engine/:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@localhost:5432/Students?schema=public
    network_mode: host

  update-student-engine:
    build: ./update-student-engine
    container_name: update-student-engine
    command: bash
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./update-student-engine/:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@localhost:5432/Students?schema=public
    network_mode: host

  db:
    container_name: students-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    network_mode: host